from pydantic import BaseModel, Field

class CacheDeletionRequest(BaseModel):
    conversation_id: str = Field(alias="ConversationId", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")