from pydantic import BaseModel, Field

class ConversationId(BaseModel):
    conversation_id: str = Field(alias="ConversationId", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")

class CacheDeletionRequest(BaseModel):
    conversation_ids: list[ConversationId] = Field(alias="ConversationIds", description="Conversation id generated by the agent")