from pydantic import BaseModel, Field

class CacheDeletionRequest(BaseModel):
    conv_id_template: str = Field(alias="ConversationIdTemplate", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")
    conv_id_state: str = Field(alias="ConversationIdState", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")
