from pydantic import BaseModel, Field

class ConversationStateResponse(BaseModel):
    ConversationId: str = Field(alias="conversation_id", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")
