from pydantic import BaseModel, Field

class ConversationStateResponse(BaseModel):
    ConversationIdTemplate: str = Field(alias="conv_id_template", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")
    ConversationIdInfo: str = Field(alias="conv_id_info", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")
