from pydantic import BaseModel, Field

class StateRequest(BaseModel):
    prompt: str = Field(alias="Prompt", pattern=r"^([a-zA-Z0-9\?\'\,\.\s\:]{1,200})$", description="Message sent to the chatbot by the user")
    conversation_id: str = Field(alias="ConversationId", pattern=r"^[a-zA-Z0-9_]{1,200}$", description="Conversation id generated by the agent")
