from openai import OpenAI
import json

api_key = "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"
model = "gpt-4o-mini"
client = OpenAI(api_key=api_key)

prompt = """
    take the following Redis Query template: 
    'Query:'
    @Tag:{} 
    @ComponentColor:{} 
    @ComponentConstantForceY:[]

    'Properties:'
    $.Components.ConstantForce.Y = 0
    $.Components.Color = '' 

    Answer only with that template
    The template is divided in two sections, Query and Properties
    The text starting with @ in the template refers to the Queries to find objects
    the text starting with $ refers to the future values that will be assigned to the objects

    You will identify the objects that need to be found, and replace those values for those in the Query template, and then find the new values to be assidned and replace them in the properties section of the template

    Example:
    1) If you are asked the following:
    'Make all green cubes float'
    You have to convert it to the following resulting template:
    @Tag:{cube} 
    @ComponentColor:{green}
    $.Components.ConstantForce.Y = 9.83

    2) If you are asked the following:
    'I want all chairs to fall to the ground'
    You have to convert it to the following resulting template:
    @Tag:{chair}
    $.Components.ConstantForce.Y = 0

    3) If you are asked the following:
    'I need all floating cubes become blue'
    You have to convert it to the following resulting template:
    @Tag:{cube} 
    @ComponentConstantForceY:[+inf 9.83]
    $.Components.Color = 'blue'

    4) If you are asked the following:
    'I need all floating cubes that are yellow to become orange and to stop levitating'
    You have to convert it to the following resulting template:
    @Tag:{cube} 
    @ComponentConstantForceY:[+inf 9.83] 
    @ComponentColor:{yellow}
    $.Components.Color = 'orange'
    $.Components.ConstantForce.Y = 0

    Have in mind that if a property is not mentioned for searching, you should not include it in the response template
    the same applies for the properties to update, if they are not mentioned, do not return them.

    After doing all of that, use the tool provided called get_formatted_gameobjects and pass as input the returned template
    Answer the user:
"""

tools = [
    {
        "type": "function",
        "name": "get_formatted_gameobjects",
        "description": "Format your response for proper handling",
        "parameters": {
            "type": "object",
            "properties": {
                "template": {
                    "type": "string",
                    "description": "A template with a Redis Query and properties to update",
                },
            },
            "required": ["template"],
        },
    },
]

def get_formatted_gameobjects(template):
    # 'Query:\n@Tag:{chair} \n@ComponentColor:{purple} \n@ComponentConstantForceY:[] \n\nProperties:\n$.Components.ConstantForce.Y = 9.83'
    query = ""
    properties = []

    from typing import Union

    class GameUpdateConfig:
        property: str
        value: Union[str | float]

    for line in template["template"].split("\n"):
        if len(line) == 0:
            continue
        if "@" == line[0] and "[]" not in line:
            query = f"{query} {line}".strip()
        if "$" == line[0]:
            update = line.split("=")
            gameupdate_config = GameUpdateConfig()
            gameupdate_config.property = update[0].strip()
            gameupdate_config.value = update[1].strip()
            properties.append(gameupdate_config)

    class GameModificationConfig():
        search_query: str
        properties_to_update: list[GameUpdateConfig]

    conf = GameModificationConfig()
    conf.search_query = query
    conf.properties_to_update = properties
    return conf

input_list = [
    {"role": "user", "content": f"{prompt} I desire you to make float all purple chairs"}
]

response = client.responses.create(
    model=model,
    tools=tools,
    input=input_list,
    tool_choice={"type": "function", "function": {"name": "get_formatted_gameobjects"}}
)

input_list += response.output

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_formatted_gameobjects":
            gameobjects = get_formatted_gameobjects(json.loads(item.arguments))
            
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({
                  "gameobjects": gameobjects
                })
            })

print("Final input:")
print(input_list)

response = client.responses.create(
    model=model,
    instructions="Respond only with a Redis template generated by a tool.",
    tools=tools,
    input=input_list,
)

print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)

output_args_json = response.choices[0].message.tool_calls[0].function.arguments
print(f"output_args_json: {output_args_json}")
