import logging
import json
from config.environment import config
from config.chat import chatgpt_client
from Orchestrator.services.tools.tool_manager import ToolManager
logging.basicConfig(level=logging.DEBUG)
logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

class ChatGPT():
    def ask(self, prompt):
        chat_history = [{"role": "user", "content": """Discern the user intent, if the user wants 
                         to know how to use the system, you will return 'instruction' if the user 
                         wants to modify the contents of the elements or to change something, you 
                         will return 'update state'. User request: {prompt}"""}]
        
        tools = ToolManager()
        response = chatgpt_client.responses.create(
            model=config.LLM_MODEL,
            tools=tools.prompt_handling_definition,
            input=chat_history,
        )

        chat_history.extend(response.output)

        # Append a specialized prompt depending on the user's intent
        chat_history.append(tools.prompt_handling(response.output))

        response = chatgpt_client.responses.create(
            model=config.LLM_MODEL,
            tools=tools.tool_definitions,
            input=chat_history,
        )

        # Append the response generated by the triggered function
        chat_history.append(tools.call_tool(response.output))

        logger.debug("Complete output:")
        logger.debug(response.model_dump_json(indent=2))
        logger.info("Chatbot Response:\n" + response.output_text)

        return json.loads(response.output_text)