import logging
import json
from config.environment import config
from config.chat import chatgpt
from Orchestrator.services.tools.tool_manager import ToolManager
logging.basicConfig(level=logging.DEBUG)
logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

class ChatGPT():
    def ask(self, prompt):
        tools = ToolManager()
        chat_history = tools.initialize_chat_history(prompt)
        
        response = chatgpt.client.responses.create(
            model=config.LLM_MODEL,
            tools=tools.prompt_handling_definition,
            input=chat_history,
        )

        # Add the initial response to the chat history
        chat_history.extend(response.output)

        # Append a specialized prompt depending on the user's intent
        chat_history.append(tools.prompt_handling(response.output_text, prompt))

        response = chatgpt.client.responses.create(
            model=config.LLM_MODEL,
            tools=tools.tool_definitions,
            input=chat_history,
        )

        # Append the response generated by the triggered function
        chat_history.append(tools.call_tool(response.output))

        logger.info("Final response: %s" + chat_history[-1]['output'])

        return json.loads(chat_history[-1]['output'])['result']