from openai import OpenAI
from config.environment import config
from core.prompt_manager import read_prompt
from services.tool_chatbot_redis import get_formatted_vr_state
import logging
import json
logging.basicConfig(level=logging.DEBUG)
logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

def ask_chatbot(prompt):
    client = OpenAI(api_key=config.LLM_API_KEY)
    instructions = "Respond only with a Redis template generated by a tool."
    prompt_config = read_prompt("few_shot_redis_query.txt")

    tools = get_tools()

    input_list = [{"role": "user", "content": f"{prompt_config} {prompt}"}]

    response = client.responses.create(
        model=config.LLM_MODEL,
        tools=tools,
        input=input_list
    )

    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_formatted_vr_state":
                vr_state = get_formatted_vr_state(json.loads(item.arguments))

                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                      "vr_state": vr_state
                    })
                })

    logger.debug("Final input:")
    logger.debug(input_list)

    response = client.responses.create(
        model=config.LLM_MODEL,
        instructions=instructions,
        tools=tools,
        input=input_list,
    )

    logger.info("Final output:")
    logger.debug(response.model_dump_json(indent=2))
    logger.info("Final output formatted:\n" + response.output_text)

    return json.loads(response.output_text)

def get_tools():
    return [
        {
            "type": "function",
            "name": "get_formatted_vr_state",
            "description": "Format your response for proper handling",
            "parameters": {
                "type": "object",
                "properties": {
                    "template": {
                        "type": "string",
                        "description": "A template with a Redis Query and properties to update",
                    },
                },
                "required": ["template"],
            },
        },
    ]